apiVersion: v1
kind: service
metadata:
  name: nginx-lb 
  spec:
    type: LoadBalancer
    selector:
      project: roboshop
      component: frontend
      environment: dev
      purpose: load-balancer 
    ports:
      - protocol: TCP
        port: 80
        targetport: 80
        nodePort: 30753